"""Generate heatmap training targets for BatDetect2 models.

This module is responsible for creating the target labels used for training
BatDetect2 models. It converts sound event annotations for an audio clip into
the specific multi-channel heatmap formats required by the neural network.

It uses a pre-configured object adhering to the `TargetProtocol` (from
`batdetect2.targets`) which encapsulates all the logic for filtering
annotations, transforming tags, encoding class names, and mapping annotation
geometry (ROIs) to target positions and sizes. This module then focuses on
rendering this information onto the heatmap grids.

The pipeline generates three core outputs for a given spectrogram:
1.  **Detection Heatmap**: Indicates presence/location of relevant sound events.
2.  **Class Heatmap**: Indicates location and class identity for specifically
    classified events.
3.  **Size Heatmap**: Encodes the target dimensions (width, height) of events.

The primary function generated by this module is a `ClipLabeller` (defined in
`.types`), which takes a `ClipAnnotation` object and its corresponding
spectrogram and returns the calculated `Heatmaps` tuple. The main configurable
parameter specific to this module is the Gaussian smoothing sigma (`sigma`)
defined in `LabelConfig`.
"""

from functools import partial
from typing import Optional

import numpy as np
import torch
from loguru import logger
from soundevent import data

from batdetect2.configs import BaseConfig, load_config
from batdetect2.typing import (
    ClipLabeller,
    Heatmaps,
    TargetProtocol,
)

__all__ = [
    "LabelConfig",
    "build_clip_labeler",
    "generate_clip_label",
    "generate_heatmaps",
    "load_label_config",
]


SIZE_DIMENSION = "dimension"
"""Dimension name for the size heatmap."""


class LabelConfig(BaseConfig):
    """Configuration parameters for heatmap generation.

    Attributes
    ----------
    sigma : float, default=3.0
        The standard deviation (in pixels/bins) of the Gaussian kernel applied
        to smooth the detection and class heatmaps. Larger values create more
        diffuse targets.
    """

    sigma: float = 3.0


def build_clip_labeler(
    targets: TargetProtocol,
    min_freq: float,
    max_freq: float,
    config: Optional[LabelConfig] = None,
) -> ClipLabeller:
    """Construct the final clip labelling function.

    This factory function prepares the callable that will perform the
    end-to-end heatmap generation for a given clip and spectrogram during
    training data loading. It takes the fully configured `targets` object and
    the `LabelConfig` and binds them to the `generate_clip_label` function.

    Parameters
    ----------
    targets : TargetProtocol
        An initialized object conforming to the `TargetProtocol`, providing all
        necessary methods for filtering, transforming, encoding, and ROI
        mapping.
    config : LabelConfig
        Configuration object containing heatmap generation parameters.

    Returns
    -------
    ClipLabeller
        A function that accepts a `data.ClipAnnotation` and `xr.DataArray`
        (spectrogram) and returns the generated `Heatmaps`.
    """
    config = config or LabelConfig()
    logger.opt(lazy=True).debug(
        "Building clip labeler with config: \n{}",
        lambda: config.to_yaml_string(),
    )
    return partial(
        generate_clip_label,
        targets=targets,
        config=config,
        min_freq=min_freq,
        max_freq=max_freq,
    )


def generate_clip_label(
    clip_annotation: data.ClipAnnotation,
    spec: torch.Tensor,
    targets: TargetProtocol,
    config: LabelConfig,
    min_freq: float,
    max_freq: float,
) -> Heatmaps:
    """Generate training heatmaps for a single annotated clip.

    This function orchestrates the target generation process for one clip:
    1. Filters and transforms sound events using `targets.filter` and
       `targets.transform`.
    2. Passes the resulting processed annotations, along with the spectrogram,
       the `targets` object, and the Gaussian `sigma` from `config`, to the
       core `generate_heatmaps` function.

    Parameters
    ----------
    clip_annotation : data.ClipAnnotation
        The complete annotation data for the audio clip, including the list
        of `sound_events` to process.
    spec : xr.DataArray
        The spectrogram corresponding to the `clip_annotation`. Must have
        'time' and 'frequency' dimensions/coordinates.
    targets : TargetProtocol
        The fully configured target definition object, providing methods for
        filtering, transformation, encoding, and ROI mapping.
    config : LabelConfig
        Configuration object providing heatmap parameters (primarily `sigma`).

    Returns
    -------
    Heatmaps
        A NamedTuple containing the generated 'detection', 'classes', and 'size'
        heatmaps for this clip.
    """
    logger.debug(
        "Will generate heatmaps for clip annotation {uuid} with {num} annotated sound events",
        uuid=clip_annotation.uuid,
        num=len(clip_annotation.sound_events),
    )

    sound_events = []

    for sound_event_annotation in clip_annotation.sound_events:
        if not targets.filter(sound_event_annotation):
            logger.debug(
                "Sound event {sound_event} did not pass the filter. Tags: {tags}",
                sound_event=sound_event_annotation,
                tags=sound_event_annotation.tags,
            )
            continue

        sound_events.append(targets.transform(sound_event_annotation))

    return generate_heatmaps(
        clip_annotation.model_copy(update=dict(sound_events=sound_events)),
        spec=spec,
        targets=targets,
        target_sigma=config.sigma,
        min_freq=min_freq,
        max_freq=max_freq,
    )


def map_to_pixels(x, size, min_val, max_val) -> int:
    return int(np.floor(np.interp(x, [min_val, max_val], [0, size])))


def generate_heatmaps(
    clip_annotation: data.ClipAnnotation,
    spec: torch.Tensor,
    targets: TargetProtocol,
    min_freq: float,
    max_freq: float,
    target_sigma: float = 3.0,
    dtype=torch.float32,
) -> Heatmaps:
    if not spec.ndim == 2:
        raise ValueError(
            "Expecting a 2-dimensional tensor of shape (H, W), "
            "H is the height of the spectrogram "
            "(frequency bins), and W is the width of the spectrogram "
            f"(temporal bins). Instead got: {spec.shape}"
        )

    height, width = spec.shape
    num_classes = len(targets.class_names)
    num_dims = len(targets.dimension_names)
    clip = clip_annotation.clip

    # Initialize heatmaps
    detection_heatmap = torch.zeros([height, width], dtype=dtype)
    class_heatmap = torch.zeros([num_classes, height, width], dtype=dtype)
    size_heatmap = torch.zeros([num_dims, height, width], dtype=dtype)

    freqs, times = torch.meshgrid(
        torch.arange(height, dtype=dtype),
        torch.arange(width, dtype=dtype),
        indexing="ij",
    )

    freqs = freqs.to(spec)
    times = times.to(spec)

    for sound_event_annotation in clip_annotation.sound_events:
        geom = sound_event_annotation.sound_event.geometry
        if geom is None:
            logger.debug(
                "Skipping annotation %s: missing geometry.",
                sound_event_annotation.uuid,
            )
            continue

        # Get the position of the sound event
        (time, frequency), size = targets.encode_roi(sound_event_annotation)

        time_index = map_to_pixels(time, width, clip.start_time, clip.end_time)
        freq_index = map_to_pixels(frequency, height, min_freq, max_freq)

        if (
            time_index < 0
            or time_index >= width
            or freq_index < 0
            or freq_index >= height
        ):
            logger.debug(
                "Skipping annotation %s: position outside spectrogram. "
                "Pos: %s",
                sound_event_annotation.uuid,
                (time, frequency),
            )
            continue

        distance = (times - time_index) ** 2 + (freqs - freq_index) ** 2
        gaussian_blob = torch.exp(-distance / (2 * target_sigma**2))

        detection_heatmap = torch.maximum(detection_heatmap, gaussian_blob)
        size_heatmap[:, freq_index, time_index] = torch.tensor(size[:])

        # Get the class name of the sound event
        try:
            class_name = targets.encode_class(sound_event_annotation)
        except ValueError as e:
            logger.warning(
                "Skipping annotation %s: Unexpected error while encoding "
                "class name %s",
                sound_event_annotation.uuid,
                e,
            )
            continue

        if class_name is None:
            # If the label is None skip the sound event
            continue

        class_index = targets.class_names.index(class_name)
        class_heatmap[class_index] = torch.maximum(
            class_heatmap[class_index],
            gaussian_blob,
        )

    return Heatmaps(
        detection=detection_heatmap,
        classes=class_heatmap,
        size=size_heatmap,
    )


def load_label_config(
    path: data.PathLike, field: Optional[str] = None
) -> LabelConfig:
    """Load the heatmap label generation configuration from a file.

    Parameters
    ----------
    path : data.PathLike
        Path to the configuration file (e.g., YAML or JSON).
    field : str, optional
        If the label configuration is nested under a specific key in the
        file, specify the key here. Defaults to None.

    Returns
    -------
    LabelConfig
        The loaded and validated label configuration object.

    Raises
    ------
    FileNotFoundError
        If the config file path does not exist.
    pydantic.ValidationError
        If the config file structure does not match the LabelConfig schema.
    """
    return load_config(path, schema=LabelConfig, field=field)
